<html>
<head>
<title>no-conditional-expect.md</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #cc7832;}
.s1 { color: #a9b7c6;}
.s2 { color: #a9b7c6;}
.s3 { color: #9876aa; font-style: italic;}
.s4 { color: #6a8759;}
</style>
</head>
<body bgcolor="#2b2b2b">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
no-conditional-expect.md</font>
</center></td></tr></table>
<pre><span class="s0"># </span><span class="s2">Prevent calling `expect` conditionally </span><span class="s1">(</span><span class="s2">`no-conditional-expect`</span><span class="s1">)</span>

<span class="s2">This rule prevents the use of `expect` in conditional blocks, such as `if`s &amp;</span>
<span class="s2">`catch`s.</span>

<span class="s2">This includes using `expect` in callbacks to functions named `catch`, which are</span>
<span class="s2">assumed to be promises.</span>

<span class="s0">## </span><span class="s2">Rule Details</span>

<span class="s2">Jest only considers a test to have failed if it throws an error, meaning if</span>
<span class="s2">calls to assertion functions like `expect` occur in conditional code such as a</span>
<span class="s2">`catch` statement, tests can end up passing but not actually test anything.</span>

<span class="s2">Additionally, conditionals tend to make tests more brittle and complex, as they</span>
<span class="s2">increase the amount of mental thinking needed to understand what is actually</span>
<span class="s2">being tested.</span>

<span class="s2">While `expect.assertions` &amp; `expect.hasAssertions` can help prevent tests from</span>
<span class="s2">silently being skipped, when combined with conditionals they typically result in</span>
<span class="s2">even more complexity being introduced.</span>

<span class="s2">The following patterns are warnings</span><span class="s1">:</span>

<span class="s0">```</span><span class="s3">js</span>
<span class="s4">it('foo', () =&gt; {</span>
  <span class="s4">doTest &amp;&amp; expect(1).toBe(2);</span>
<span class="s4">});</span>

<span class="s4">it('bar', () =&gt; {</span>
  <span class="s4">if (!skipTest) {</span>
    <span class="s4">expect(1).toEqual(2);</span>
  <span class="s4">}</span>
<span class="s4">});</span>

<span class="s4">it('baz', async () =&gt; {</span>
  <span class="s4">try {</span>
    <span class="s4">await foo();</span>
  <span class="s4">} catch (err) {</span>
    <span class="s4">expect(err).toMatchObject({ code: 'MODULE_NOT_FOUND' });</span>
  <span class="s4">}</span>
<span class="s4">});</span>

<span class="s4">it('throws an error', async () =&gt; {</span>
  <span class="s4">await foo().catch(error =&gt; expect(error).toBeInstanceOf(error));</span>
<span class="s4">});</span>
<span class="s0">```</span>

<span class="s2">The following patterns are not warnings</span><span class="s1">:</span>

<span class="s0">```</span><span class="s3">js</span>
<span class="s4">it('foo', () =&gt; {</span>
  <span class="s4">expect(!value).toBe(false);</span>
<span class="s4">});</span>

<span class="s4">function getValue() {</span>
  <span class="s4">if (process.env.FAIL) {</span>
    <span class="s4">return 1;</span>
  <span class="s4">}</span>

  <span class="s4">return 2;</span>
<span class="s4">}</span>

<span class="s4">it('foo', () =&gt; {</span>
  <span class="s4">expect(getValue()).toBe(2);</span>
<span class="s4">});</span>

<span class="s4">it('validates the request', () =&gt; {</span>
  <span class="s4">try {</span>
    <span class="s4">processRequest(request);</span>
  <span class="s4">} catch {</span>
    <span class="s4">// ignore errors</span>
  <span class="s4">} finally {</span>
    <span class="s4">expect(validRequest).toHaveBeenCalledWith(request);</span>
  <span class="s4">}</span>
<span class="s4">});</span>

<span class="s4">it('throws an error', async () =&gt; {</span>
  <span class="s4">await expect(foo).rejects.toThrow(Error);</span>
<span class="s4">});</span>
<span class="s0">```</span>

<span class="s0">### </span><span class="s2">How to catch a thrown error for testing without violating this rule</span>

<span class="s2">A common situation that comes up with this rule is when wanting to test</span>
<span class="s2">properties on a thrown error, as Jest's `toThrow` matcher only checks the</span>
<span class="s2">`message` property.</span>

<span class="s2">Most people write something like this</span><span class="s1">:</span>

<span class="s0">```</span><span class="s3">typescript</span>
<span class="s4">describe('when the http request fails', () =&gt; {</span>
  <span class="s4">it('includes the status code in the error', async () =&gt; {</span>
    <span class="s4">try {</span>
      <span class="s4">await makeRequest(url);</span>
    <span class="s4">} catch (error) {</span>
      <span class="s4">expect(error).toHaveProperty('statusCode', 404);</span>
    <span class="s4">}</span>
  <span class="s4">});</span>
<span class="s4">});</span>
<span class="s0">```</span>

<span class="s2">As stated above, the problem with this is that if `makeRequest</span><span class="s1">()</span><span class="s2">` doesn't throw</span>
<span class="s2">the test will still pass as if the `expect` had been called.</span>

<span class="s2">While you can use `expect.assertions` &amp; `expect.hasAssertions` for these</span>
<span class="s2">situations, they only work with `expect`.</span>

<span class="s2">A better way to handle this situation is to introduce a wrapper to handle the</span>
<span class="s2">catching, and otherwise return a specific </span><span class="s1">&quot;</span><span class="s2">no error thrown</span><span class="s1">&quot; </span><span class="s2">error if nothing is</span>
<span class="s2">thrown by the wrapped function</span><span class="s1">:</span>

<span class="s0">```</span><span class="s3">typescript</span>
<span class="s4">class NoErrorThrownError extends Error {}</span>

<span class="s4">const getError = async &lt;TError&gt;(call: () =&gt; unknown): Promise&lt;TError&gt; =&gt; {</span>
  <span class="s4">try {</span>
    <span class="s4">await call();</span>

    <span class="s4">throw new NoErrorThrownError();</span>
  <span class="s4">} catch (error: unknown) {</span>
    <span class="s4">return error as TError;</span>
  <span class="s4">}</span>
<span class="s4">};</span>

<span class="s4">describe('when the http request fails', () =&gt; {</span>
  <span class="s4">it('includes the status code in the error', async () =&gt; {</span>
    <span class="s4">const error = await getError(async () =&gt; makeRequest(url));</span>

    <span class="s4">// check that the returned error wasn't that no error was thrown</span>
    <span class="s4">expect(error).not.toBeInstanceOf(NoErrorThrownError);</span>
    <span class="s4">expect(error).toHaveProperty('statusCode', 404);</span>
  <span class="s4">});</span>
<span class="s4">});</span>
<span class="s0">```</span>
</pre>
</body>
</html>